### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kmahl** [codediodeio/angular-firestarter#3]
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined

**Comment by codediodeio** [comment]
I'm assuming this is coming from the upload-form.component.ts. 

`let filesIndex = _.range(files.length)`

We might want to return if files are empty using lodash, such as 
if (_.isEmpty(files)) return;

I can fix this soon, unless you want handle it and send a pull request.

**Comment by alibahjat** [comment]
is there any solution for this problem

**Comment by codediodeio** [comment]
This should be resolved with the latest commit.  Let me know if you still get the error and please paste the stack trace.

**Comment by blackbeario** [comment]
I'm still getting this with the latest branch.

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:15457:109)
    at parseSourceFileWorker (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:15389:26)
    at Object.parseSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:15338:26)
    at Object.createSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:15192:29)
    at VirtualFileStats.getSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/@ngtools/webpack/src/compiler_host.js:66:35)
    at WebpackCompilerHost.getSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/@ngtools/webpack/src/compiler_host.js:191:38)
    at findSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67909:29)
    at processImportedModules (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67937:17)
    at processSourceFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67840:27)
    at processRootFile (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67728:13)
    at /Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67018:60
    at Object.forEach (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:1449:30)
    at Object.createProgram (/Users/jfraz/Sites/angular-firestarter/node_modules/typescript/lib/typescript.js:67018:16)
    at AotPlugin._setupOptions (/Users/jfraz/Sites/angular-firestarter/node_modules/@ngtools/webpack/src/plugin.js:143:28)
    at new AotPlugin (/Users/jfraz/Sites/angular-firestarter/node_modules/@ngtools/webpack/src/plugin.js:30:14)
    at _createAotPlugin (/Users/jfraz/Sites/angular-firestarter/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.exports.getNonAotConfig (/Users/jfraz/Sites/angular-firestarter/node_modules/@angular/cli/models/webpack-configs/typescript.js:72:19)
    at NgCliWebpackConfig.buildConfig (/Users/jfraz/Sites/angular-firestarter/node_modules/@angular/cli/models/webpack-config.js:29:37)
    at Class.run (/Users/jfraz/Sites/angular-firestarter/node_modules/@angular/cli/tasks/serve.js:71:98)
