### ISSUE TITLE
ng build --prod

### ISSUE THREAD

**Issue by rroslan** [codediodeio/angular-firestarter#40]
at Object.createSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:16371:29)
    at VirtualFileStats.getSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\@ngtools\webpack\src\compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\@ngtools\webpack\src\compiler_host.js:207:38)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getOriginalSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:226:31)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:318:23)
    at findSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70246:29)
    at processImportedModules (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70393:25)
    at findSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70274:17)
    at processImportedModules (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70393:25)
    at findSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70274:17)
    at args (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70173:34)
    at processSourceFile (D:\code\WebStormProjects\angular-firestarter\node_modules\typescript\lib\typescript.js:70200:13)

**Comment by rroslan** [comment]
Sorry, ng build works, without the --prod

**Comment by dleonard00** [comment]
looking at the package.json you may be running `ng build --prod` when you run `ng build`

```
...
"scripts": {
    "ng": "ng",
    "start": "ng serve --aot",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "pwa": "ng build --prod && sw-precache --root=dist --config=precache-config.js"
  },
...
```
If this is no longer an issue for you, consider closing the issue.
