### ISSUE TITLE
codediodeio/angular-firestarter: error when installing git clone https://github.com/codediodeio/angular-firestarter.git firestarter

### ISSUE THREAD

**Issue by HerveGagnon** [codediodeio/angular-firestarter#69]
ng --version
Your global Angular CLI version (7.0.2) is greater than your local
version (6.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.1
Node: 10.7.0
OS: darwin x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/pwa                      0.6.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

and I am getting the following error:

ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
    at Object.sassLoader (/Users/hervegagnon/project/internal/angularFire/firestarter/node_modules/sass-loader/lib/loader.js:31:19)
ERROR in src/app/core/auth.service.ts(5,22): error TS2307: Cannot find module 'firebase'.

**Comment by jorgencnc** [comment]
ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.4
    at module.exports (C:\firestarter\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\firestarter\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (C:\firestarter\node_modules\sass-loader\lib\loader.js:46:72)
ERROR in node_modules/@angular/fire/auth/auth.d.ts(4,28): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/firebase.app.module.d.ts(2,79): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/firestore/collection/collection.d.ts(2,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/firestore/document/document.d.ts(5,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/firestore/firestore.d.ts(7,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/firestore/interfaces.d.ts(2,27): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/storage/interfaces.d.ts(1,25): error TS2307: Cannot find module 'firebase/app'.
node_modules/@angular/fire/storage/observable/fromTask.d.ts(3,25): error TS2307: Cannot find module 'firebase/app'.
src/app/core/auth.service.ts(5,22): error TS2307: Cannot find module 'firebase'.
